security:
  oauth2:
    client:
      registration:
        naver:
          client-id: "UdgcXVojO1LT7djY4u9Z"
          client-secret: "ulMrvrzNKc"
          redirect-uri: "http://localhost:8080/login/social/{registrationId}"
          authorization-grant-type: authorization_code
          scope: name, email
          client-name: Naver
      provider:
        naver:
          authorization-uri: https://nid.naver.com/oauth2.0/authorize
          token-uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
          user-name-attribute: response

